networks:
  blog:
    name: blog
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
services:
  vuepress-webhook:
    container_name: vuepress-webhook
    build: .
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    #command: sh -c "node test.js; tail -f /dev/null"
    restart: always

