networks:
  blog:
    name: blog
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
services:
  vuepress-webhook:
    container_name: vuepress-webhook
    build: .
    volumes:
      - .:/app
      - ~/.ssh:/home/appuser/.ssh:ro
    environment:
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    ports:
      - "3030:3030"
    restart: always

